version: "3.8"

services:
  jericho:
    build:
      context: ./jericho
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GAME_FILE=${GAME_FILE}

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama  # persist models between restarts

  zorkinator:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - ollama
    volumes:
      - .:/app
    working_dir: /app
    environment:
      - OLLAMA_API=http://ollama:11434
      - JERICHO_API=http://zork-api:8000
    tty: true

volumes:
  ollama_models: