services:
  jericho:
    build:
      context: ./jericho
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GAME_FILE=${GAME_FILE}
    volumes:
      - ./jericho/games/z-machine-games-master/jericho-game-suite:/app/games

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - ${OLLAMA_PORT}:${OLLAMA_PORT}
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    volumes:
      - ${OLLAMA_DIR}:/root/.ollama
      - ./llm/ollama/entrypoint.sh:/entrypoint.sh
    entrypoint: [ "bash", "/entrypoint.sh" ]

  heuristics:
    build:
      context: ./heuristics
      dockerfile: dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./heuristics:/app
    working_dir: /app
    tty: true

  zorkinator:
    build:
      context: ./zorkinator
      dockerfile: dockerfile
    depends_on:
      - jericho
      - ollama
    environment:
      - OLLAMA_API=http://ollama:11434
      - JERICHO_API=http://jericho:8000
    tty: true

volumes:
  ollama_models: