version: "3.8"

services:
  jericho:
    build:
      context: ./jericho
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - GAME_FILE=${GAME_FILE}
    volumes:
      - ./jericho/games/z-machine-games-master/jericho-game-suite:/app/games

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ${HOME}/.ollama:/root/.ollama
      - ollama_models:/data

  zorkinator:
    build:
      context: ./zorkinator
      dockerfile: dockerfile
    depends_on:
      - jericho
      - ollama
    environment:
      - OLLAMA_API=http://ollama:11434
      - JERICHO_API=http://jericho:8000
    tty: true

volumes:
  ollama_models:
