version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    volumes:
      - ${OLLAMA_DIR}:/root/.ollama
      - ./llm/ollama/entrypoint.sh:/entrypoint.sh
    entrypoint: [ "bash", "/entrypoint.sh" ]