version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_MODEL=${OLLAMA_MODEL}
    volumes:
      - ${OLLAMA_DIR}:/root/.ollama
    entrypoint: >
      bash -c '
        echo "▶ Starting Ollama server..." &&
        ollama serve & 

        echo "⏳ Waiting for Ollama server..." &&
        until ollama list > /dev/null 2>&1; do
          echo "… server not ready" && sleep 1
        done

        echo "✅ Pulling model: $OLLAMA_MODEL" &&
        ollama pull "$OLLAMA_MODEL"

        echo "📡 Server ready and model pulled. Holding open..."
        tail -f /dev/null
      '