- name: Deploy Ollama to workers
  hosts: workers
  become: true
  tasks:
    - name: Create deployment directory
      file:
        path: /opt/ollama
        state: directory

    - name: Template docker-compose for each worker
      template:
        src: templates/docker-compose.yml.j2
        dest: /opt/ollama/docker-compose.yml

    - name: Run Docker Compose
      shell: docker compose up -d
      args:
        chdir: /opt/ollama
