  heuristics:
    build:
      context: ./heuristics
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./heuristics:/app
    working_dir: /app
    environment:
      - MODE=dev
    tty: true
